module.exports = {
  list: require("./list"),
  category: require("./category"),
  read: require("./post"),
  write: require("./write"),
  withdrawal: require("./withdrawNewsPost"),
  modification: require("./modifyNewsPost"),
  writeComment: require("./writeComment"),
  modifyComment: require("./modifyComment"),
  withdrawalComment: require("./withdrawComment"),
  myList: require("./myList"),
  img: require("./img"),
  myComment: require("./myComment"),
  search: require("./search"),
};
