module.exports = {
  list: require("./list"),
  nomalOrNot: require("./nomalOrNot"),
  read: require("./post"),
  write: require("./write"),
  modifynomal: require("./modifynomal"),
  img: require("./img"),
  delete: require("./withdrawal"),
  state: require("./modifyState"),
  modifyTrade: require("./modifyTrade"),
  suggestion: require("./suggestion"),
  modifyCost: require("./modifyCost"),
  suggestionDelete: require("./withdrawSuggestion"),
  like: require("./like"),
  deleteLike: require("./withdrawLike"),
};
