module.exports = {
  list: require("./list"),
  normalOrNot: require("./normalOrNot"),
  read: require("./post"),
  write: require("./write"),
  modifynormal: require("./modifynormal"),
  img: require("./img"),
  delete: require("./withdrawal"),
  state: require("./modifyState"),
  modifyTrade: require("./modifyTrade"),
  suggestion: require("./suggestion"),
  modifyCost: require("./modifyCost"),
  suggestionDelete: require("./withdrawSuggestion"),
  like: require("./like"),
  deleteLike: require("./withdrawLike"),
  myList: require("./myList"),
  myLike: require("./myLike"),
  search: require("./search"),
};
